

# This file was generated by zbuildgen. Don't edit this file! Edit "SimRobotCore2.make.zbuild" instead.


SOLUTIONDIR ?= $(CURDIR)

ifeq ($(CONFIG),Debug)

PROJECTNAME := SimRobotCore2
CONFIG := Debug
OUTDIR := $(SOLUTIONDIR)/../Build/SimRobotCore2/Linux/$(CONFIG)
INTDIR := $(SOLUTIONDIR)/../Build/SimRobotCore2/Linux/$(CONFIG)
TARGET := $(OUTDIR)/libSimRobotCore2.so
OBJECTS := \
	$(INTDIR)/moc_ActuatorsWidget.o\
	$(INTDIR)/moc_SensorWidget.o\
	$(INTDIR)/moc_SimObjectWidget.o\
	$(INTDIR)/qrc_SimRobotCore2.o\
	$(INTDIR)/ActuatorsWidget.o\
	$(INTDIR)/CoreModule.o\
	$(INTDIR)/Camera.o\
	$(INTDIR)/Joint.o\
	$(INTDIR)/PhysicalObject.o\
	$(INTDIR)/DepthImageSensor.o\
	$(INTDIR)/Texture.o\
	$(INTDIR)/SimObjectWidget.o\
	$(INTDIR)/Appearance.o\
	$(INTDIR)/SphereAppearance.o\
	$(INTDIR)/BoxGeometry.o\
	$(INTDIR)/Parser.o\
	$(INTDIR)/Assert.o\
	$(INTDIR)/System.o\
	$(INTDIR)/BoxMass.o\
	$(INTDIR)/Scene.o\
	$(INTDIR)/SingleDistanceSensor.o\
	$(INTDIR)/CylinderGeometry.o\
	$(INTDIR)/InertiaMatrixMass.o\
	$(INTDIR)/BoxAppearance.o\
	$(INTDIR)/Axis.o\
	$(INTDIR)/Sensor.o\
	$(INTDIR)/SimObject.o\
	$(INTDIR)/Geometry.o\
	$(INTDIR)/Mass.o\
	$(INTDIR)/Vector3.o\
	$(INTDIR)/Accelerometer.o\
	$(INTDIR)/Simulation.o\
	$(INTDIR)/SphereGeometry.o\
	$(INTDIR)/SphereMass.o\
	$(INTDIR)/ComplexAppearance.o\
	$(INTDIR)/Body.o\
	$(INTDIR)/OpenGLTools.o\
	$(INTDIR)/Element.o\
	$(INTDIR)/Reader.o\
	$(INTDIR)/OffscreenRenderer.o\
	$(INTDIR)/GraphicalObject.o\
	$(INTDIR)/Matrix3x3.o\
	$(INTDIR)/Gyroscope.o\
	$(INTDIR)/PrimaryObject.o\
	$(INTDIR)/ApproxDistanceSensor.o\
	$(INTDIR)/ServoMotor.o\
	$(INTDIR)/Bumper.o\
	$(INTDIR)/SensorWidget.o\
	$(INTDIR)/Hinge.o\
	$(INTDIR)/Actuator.o\
	$(INTDIR)/CylinderAppearance.o\
	$(INTDIR)/Compound.o\
	$(INTDIR)/SimObjectRenderer.o\
	$(INTDIR)/VelocityMotor.o\
	$(INTDIR)/Slider.o\

PCHOBJECT := 
CUSTOMOBJECTS := \
	$(INTDIR)/qrc_SimRobotCore2.cpp\
	$(INTDIR)/moc_SensorWidget.cpp\
	$(INTDIR)/moc_ActuatorsWidget.cpp\
	$(INTDIR)/moc_SimObjectWidget.cpp\

DEPENDENCIES := 

DEFINES := -D"LINUX" -D"QT_NO_DEBUG" -D"QT_SHARED" -D"QT_OPENGL_LIB" -D"QT_GUI_LIB" -D"QT_CORE_LIB" -D"DEBUG" -D"_DEBUG"
INCPATHS := -I"$(INTDIR)" -I"../Src/SimRobotCore2" -I"../Util/glew/Linux/include" -I"../Util/libxml2/include" -I"../Util/ode/Linux/include" -I"/usr/include/qt4/QtCore" -I"/usr/include/qt4/QtGui" -I"/usr/include/qt4/QtOpenGL" -I"/usr/include/qt4"
LIBPATHS := -L"../Util/ode/Linux/lib32" -L"../Util/ode/Linux/lib64" -L"../Util/glew/Linux/lib" -L"../Util/libxml2/Linux/lib"
LIBS := -lrt -lpthread -lode -lGLEW -lxml2 -lQtGui -lQtCore -lQtOpenGL -lGLU -lGL

BUILDFLAGS := -MMD $(DEFINES) $(INCPATHS)   -fpic -pipe -Wall -W -Wno-unused-parameter -Wno-non-virtual-dtor -Wno-deprecated -Wno-ignored-qualifiers -g
LINKFLAGS :=  -shared -fpic  $(LIBPATHS) $(LIBS)

.PHONY: all prebuild clean dist distclean

all: $(TARGET)

$(TARGET): $(OBJECTS) $(CUSTOMOBJECTS) $(DEPENDENCIES)
	@echo Linking...
	@$(CXX) -o $@ $(OBJECTS) $(LDFLAGS) $(LINKFLAGS) 

$(INTDIR)/moc_ActuatorsWidget.o: $(INTDIR)/moc_ActuatorsWidget.cpp  | prebuild
	@echo "moc_ActuatorsWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SensorWidget.o: $(INTDIR)/moc_SensorWidget.cpp  | prebuild
	@echo "moc_SensorWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SimObjectWidget.o: $(INTDIR)/moc_SimObjectWidget.cpp  | prebuild
	@echo "moc_SimObjectWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobotCore2.o: $(INTDIR)/qrc_SimRobotCore2.cpp  | prebuild
	@echo "qrc_SimRobotCore2.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ActuatorsWidget.o: ../Src/SimRobotCore2/ActuatorsWidget.cpp  | prebuild
	@echo "ActuatorsWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CoreModule.o: ../Src/SimRobotCore2/CoreModule.cpp  | prebuild
	@echo "CoreModule.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Camera.o: ../Src/SimRobotCore2/Simulation/Sensors/Camera.cpp  | prebuild
	@echo "Camera.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Joint.o: ../Src/SimRobotCore2/Simulation/Joints/Joint.cpp  | prebuild
	@echo "Joint.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/PhysicalObject.o: ../Src/SimRobotCore2/Simulation/PhysicalObject.cpp  | prebuild
	@echo "PhysicalObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/DepthImageSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/DepthImageSensor.cpp  | prebuild
	@echo "DepthImageSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Texture.o: ../Src/SimRobotCore2/Tools/Texture.cpp  | prebuild
	@echo "Texture.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObjectWidget.o: ../Src/SimRobotCore2/SimObjectWidget.cpp  | prebuild
	@echo "SimObjectWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Appearance.o: ../Src/SimRobotCore2/Simulation/Appearances/Appearance.cpp  | prebuild
	@echo "Appearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/SphereAppearance.cpp  | prebuild
	@echo "SphereAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/BoxGeometry.cpp  | prebuild
	@echo "BoxGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Parser.o: ../Src/SimRobotCore2/Parser/Parser.cpp  | prebuild
	@echo "Parser.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Assert.o: ../Src/SimRobotCore2/Platform/Assert.cpp  | prebuild
	@echo "Assert.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/System.o: ../Src/SimRobotCore2/Platform/System.cpp  | prebuild
	@echo "System.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxMass.o: ../Src/SimRobotCore2/Simulation/Masses/BoxMass.cpp  | prebuild
	@echo "BoxMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Scene.o: ../Src/SimRobotCore2/Simulation/Scene.cpp  | prebuild
	@echo "Scene.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SingleDistanceSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/SingleDistanceSensor.cpp  | prebuild
	@echo "SingleDistanceSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CylinderGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/CylinderGeometry.cpp  | prebuild
	@echo "CylinderGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/InertiaMatrixMass.o: ../Src/SimRobotCore2/Simulation/Masses/InertiaMatrixMass.cpp  | prebuild
	@echo "InertiaMatrixMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/BoxAppearance.cpp  | prebuild
	@echo "BoxAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Axis.o: ../Src/SimRobotCore2/Simulation/Axis.cpp  | prebuild
	@echo "Axis.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Sensor.o: ../Src/SimRobotCore2/Simulation/Sensor.cpp  | prebuild
	@echo "Sensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObject.o: ../Src/SimRobotCore2/Simulation/SimObject.cpp  | prebuild
	@echo "SimObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Geometry.o: ../Src/SimRobotCore2/Simulation/Geometries/Geometry.cpp  | prebuild
	@echo "Geometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Mass.o: ../Src/SimRobotCore2/Simulation/Masses/Mass.cpp  | prebuild
	@echo "Mass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Vector3.o: ../Src/SimRobotCore2/Tools/Vector3.cpp  | prebuild
	@echo "Vector3.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Accelerometer.o: ../Src/SimRobotCore2/Simulation/Sensors/Accelerometer.cpp  | prebuild
	@echo "Accelerometer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Simulation.o: ../Src/SimRobotCore2/Simulation/Simulation.cpp  | prebuild
	@echo "Simulation.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/SphereGeometry.cpp  | prebuild
	@echo "SphereGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereMass.o: ../Src/SimRobotCore2/Simulation/Masses/SphereMass.cpp  | prebuild
	@echo "SphereMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ComplexAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/ComplexAppearance.cpp  | prebuild
	@echo "ComplexAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Body.o: ../Src/SimRobotCore2/Simulation/Body.cpp  | prebuild
	@echo "Body.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/OpenGLTools.o: ../Src/SimRobotCore2/Tools/OpenGLTools.cpp  | prebuild
	@echo "OpenGLTools.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Element.o: ../Src/SimRobotCore2/Parser/Element.cpp  | prebuild
	@echo "Element.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Reader.o: ../Src/SimRobotCore2/Parser/Reader.cpp  | prebuild
	@echo "Reader.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/OffscreenRenderer.o: ../Src/SimRobotCore2/Platform/OffscreenRenderer.cpp  | prebuild
	@echo "OffscreenRenderer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/GraphicalObject.o: ../Src/SimRobotCore2/Simulation/GraphicalObject.cpp  | prebuild
	@echo "GraphicalObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Matrix3x3.o: ../Src/SimRobotCore2/Tools/Matrix3x3.cpp  | prebuild
	@echo "Matrix3x3.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Gyroscope.o: ../Src/SimRobotCore2/Simulation/Sensors/Gyroscope.cpp  | prebuild
	@echo "Gyroscope.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/PrimaryObject.o: ../Src/SimRobotCore2/Simulation/PrimaryObject.cpp  | prebuild
	@echo "PrimaryObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ApproxDistanceSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/ApproxDistanceSensor.cpp  | prebuild
	@echo "ApproxDistanceSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ServoMotor.o: ../Src/SimRobotCore2/Simulation/Motors/ServoMotor.cpp  | prebuild
	@echo "ServoMotor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Bumper.o: ../Src/SimRobotCore2/Simulation/Sensors/Bumper.cpp  | prebuild
	@echo "Bumper.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SensorWidget.o: ../Src/SimRobotCore2/SensorWidget.cpp  | prebuild
	@echo "SensorWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Hinge.o: ../Src/SimRobotCore2/Simulation/Joints/Hinge.cpp  | prebuild
	@echo "Hinge.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Actuator.o: ../Src/SimRobotCore2/Simulation/Actuator.cpp  | prebuild
	@echo "Actuator.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CylinderAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/CylinderAppearance.cpp  | prebuild
	@echo "CylinderAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Compound.o: ../Src/SimRobotCore2/Simulation/Compound.cpp  | prebuild
	@echo "Compound.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObjectRenderer.o: ../Src/SimRobotCore2/SimObjectRenderer.cpp  | prebuild
	@echo "SimObjectRenderer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/VelocityMotor.o: ../Src/SimRobotCore2/Simulation/Motors/VelocityMotor.cpp  | prebuild
	@echo "VelocityMotor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Slider.o: ../Src/SimRobotCore2/Simulation/Joints/Slider.cpp  | prebuild
	@echo "Slider.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobotCore2.cpp: ../Src/SimRobotCore2/SimRobotCore2.qrc ../Src/SimRobotCore2/Icons/DragPlane.png ../Src/SimRobotCore2/Icons/arrow_rotate_clockwise.png ../Src/SimRobotCore2/Icons/brick.png ../Src/SimRobotCore2/Icons/bricks.png ../Src/SimRobotCore2/Icons/camera.png ../Src/SimRobotCore2/Icons/chart_line.png ../Src/SimRobotCore2/Icons/layers.png ../Src/SimRobotCore2/Icons/link.png ../Src/SimRobotCore2/Icons/note.png ../Src/SimRobotCore2/Icons/opening_angle.png ../Src/SimRobotCore2/Icons/slider.png ../Src/SimRobotCore2/Icons/transmit_go.png ../Src/SimRobotCore2/SimRobotCore2.qrc | prebuild
	@echo "SimRobotCore2.qrc (Qt rcc)"
	@rcc -name SimRobotCore2 ../Src/SimRobotCore2/SimRobotCore2.qrc -o $(INTDIR)/qrc_SimRobotCore2.cpp

$(INTDIR)/moc_SensorWidget.cpp: ../Src/SimRobotCore2/SensorWidget.h  | prebuild
	@echo "SensorWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DDEBUG -D_DEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/SensorWidget.h -o $(INTDIR)/moc_SensorWidget.cpp

$(INTDIR)/moc_ActuatorsWidget.cpp: ../Src/SimRobotCore2/ActuatorsWidget.h  | prebuild
	@echo "ActuatorsWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DDEBUG -D_DEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/ActuatorsWidget.h -o $(INTDIR)/moc_ActuatorsWidget.cpp

$(INTDIR)/moc_SimObjectWidget.cpp: ../Src/SimRobotCore2/SimObjectWidget.h  | prebuild
	@echo "SimObjectWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DDEBUG -D_DEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/SimObjectWidget.h -o $(INTDIR)/moc_SimObjectWidget.cpp

$(INTDIR):
	@mkdir -p $(INTDIR)

ifneq ($(INTDIR),$(OUTDIR))
$(OUTDIR):
	@mkdir -p $(OUTDIR)
endif

prebuild: $(INTDIR) $(OUTDIR)
	@echo "------ Building $(PROJECTNAME) ($(CONFIG)) ------"

clean:
	@echo "------ Cleaning $(PROJECTNAME) ($(CONFIG)) ------"
	@echo Cleaning...
	-@rm -rf $(OBJECTS) $(PCHOBJECT) $(CUSTOMOBJECTS) $(TARGET) $(OBJECTS:%.o=%.d) $(PCHOBJECT:%.gch=%.d)

-include $(OBJECTS:%.o=%.d)

else

PROJECTNAME := SimRobotCore2
CONFIG := Release
OUTDIR := $(SOLUTIONDIR)/../Build/SimRobotCore2/Linux/$(CONFIG)
INTDIR := $(SOLUTIONDIR)/../Build/SimRobotCore2/Linux/$(CONFIG)
TARGET := $(OUTDIR)/libSimRobotCore2.so
OBJECTS := \
	$(INTDIR)/moc_ActuatorsWidget.o\
	$(INTDIR)/moc_SensorWidget.o\
	$(INTDIR)/moc_SimObjectWidget.o\
	$(INTDIR)/qrc_SimRobotCore2.o\
	$(INTDIR)/ActuatorsWidget.o\
	$(INTDIR)/CoreModule.o\
	$(INTDIR)/Camera.o\
	$(INTDIR)/Joint.o\
	$(INTDIR)/PhysicalObject.o\
	$(INTDIR)/DepthImageSensor.o\
	$(INTDIR)/Texture.o\
	$(INTDIR)/SimObjectWidget.o\
	$(INTDIR)/Appearance.o\
	$(INTDIR)/SphereAppearance.o\
	$(INTDIR)/BoxGeometry.o\
	$(INTDIR)/Parser.o\
	$(INTDIR)/Assert.o\
	$(INTDIR)/System.o\
	$(INTDIR)/BoxMass.o\
	$(INTDIR)/Scene.o\
	$(INTDIR)/SingleDistanceSensor.o\
	$(INTDIR)/CylinderGeometry.o\
	$(INTDIR)/InertiaMatrixMass.o\
	$(INTDIR)/BoxAppearance.o\
	$(INTDIR)/Axis.o\
	$(INTDIR)/Sensor.o\
	$(INTDIR)/SimObject.o\
	$(INTDIR)/Geometry.o\
	$(INTDIR)/Mass.o\
	$(INTDIR)/Vector3.o\
	$(INTDIR)/Accelerometer.o\
	$(INTDIR)/Simulation.o\
	$(INTDIR)/SphereGeometry.o\
	$(INTDIR)/SphereMass.o\
	$(INTDIR)/ComplexAppearance.o\
	$(INTDIR)/Body.o\
	$(INTDIR)/OpenGLTools.o\
	$(INTDIR)/Element.o\
	$(INTDIR)/Reader.o\
	$(INTDIR)/OffscreenRenderer.o\
	$(INTDIR)/GraphicalObject.o\
	$(INTDIR)/Matrix3x3.o\
	$(INTDIR)/Gyroscope.o\
	$(INTDIR)/PrimaryObject.o\
	$(INTDIR)/ApproxDistanceSensor.o\
	$(INTDIR)/ServoMotor.o\
	$(INTDIR)/Bumper.o\
	$(INTDIR)/SensorWidget.o\
	$(INTDIR)/Hinge.o\
	$(INTDIR)/Actuator.o\
	$(INTDIR)/CylinderAppearance.o\
	$(INTDIR)/Compound.o\
	$(INTDIR)/SimObjectRenderer.o\
	$(INTDIR)/VelocityMotor.o\
	$(INTDIR)/Slider.o\

PCHOBJECT := 
CUSTOMOBJECTS := \
	$(INTDIR)/qrc_SimRobotCore2.cpp\
	$(INTDIR)/moc_SensorWidget.cpp\
	$(INTDIR)/moc_ActuatorsWidget.cpp\
	$(INTDIR)/moc_SimObjectWidget.cpp\

DEPENDENCIES := 

DEFINES := -D"LINUX" -D"QT_NO_DEBUG" -D"QT_SHARED" -D"QT_OPENGL_LIB" -D"QT_GUI_LIB" -D"QT_CORE_LIB" -D"NDEBUG"
INCPATHS := -I"$(INTDIR)" -I"../Src/SimRobotCore2" -I"../Util/glew/Linux/include" -I"../Util/libxml2/include" -I"../Util/ode/Linux/include" -I"/usr/include/qt4/QtCore" -I"/usr/include/qt4/QtGui" -I"/usr/include/qt4/QtOpenGL" -I"/usr/include/qt4"
LIBPATHS := -L"../Util/ode/Linux/lib32" -L"../Util/ode/Linux/lib64" -L"../Util/glew/Linux/lib" -L"../Util/libxml2/Linux/lib"
LIBS := -lrt -lpthread -lode -lGLEW -lxml2 -lQtGui -lQtCore -lQtOpenGL -lGLU -lGL

BUILDFLAGS := -MMD $(DEFINES) $(INCPATHS)   -fpic -pipe -Wall -W -Wno-unused-parameter -Wno-non-virtual-dtor -Wno-deprecated -Wno-ignored-qualifiers -Wno-unused -O3 -fomit-frame-pointer
LINKFLAGS :=  -shared -fpic -s $(LIBPATHS) $(LIBS)

.PHONY: all prebuild clean dist distclean

all: $(TARGET)

$(TARGET): $(OBJECTS) $(CUSTOMOBJECTS) $(DEPENDENCIES)
	@echo Linking...
	@$(CXX) -o $@ $(OBJECTS) $(LDFLAGS) $(LINKFLAGS) 

$(INTDIR)/moc_ActuatorsWidget.o: $(INTDIR)/moc_ActuatorsWidget.cpp  | prebuild
	@echo "moc_ActuatorsWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SensorWidget.o: $(INTDIR)/moc_SensorWidget.cpp  | prebuild
	@echo "moc_SensorWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SimObjectWidget.o: $(INTDIR)/moc_SimObjectWidget.cpp  | prebuild
	@echo "moc_SimObjectWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobotCore2.o: $(INTDIR)/qrc_SimRobotCore2.cpp  | prebuild
	@echo "qrc_SimRobotCore2.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ActuatorsWidget.o: ../Src/SimRobotCore2/ActuatorsWidget.cpp  | prebuild
	@echo "ActuatorsWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CoreModule.o: ../Src/SimRobotCore2/CoreModule.cpp  | prebuild
	@echo "CoreModule.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Camera.o: ../Src/SimRobotCore2/Simulation/Sensors/Camera.cpp  | prebuild
	@echo "Camera.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Joint.o: ../Src/SimRobotCore2/Simulation/Joints/Joint.cpp  | prebuild
	@echo "Joint.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/PhysicalObject.o: ../Src/SimRobotCore2/Simulation/PhysicalObject.cpp  | prebuild
	@echo "PhysicalObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/DepthImageSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/DepthImageSensor.cpp  | prebuild
	@echo "DepthImageSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Texture.o: ../Src/SimRobotCore2/Tools/Texture.cpp  | prebuild
	@echo "Texture.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObjectWidget.o: ../Src/SimRobotCore2/SimObjectWidget.cpp  | prebuild
	@echo "SimObjectWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Appearance.o: ../Src/SimRobotCore2/Simulation/Appearances/Appearance.cpp  | prebuild
	@echo "Appearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/SphereAppearance.cpp  | prebuild
	@echo "SphereAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/BoxGeometry.cpp  | prebuild
	@echo "BoxGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Parser.o: ../Src/SimRobotCore2/Parser/Parser.cpp  | prebuild
	@echo "Parser.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Assert.o: ../Src/SimRobotCore2/Platform/Assert.cpp  | prebuild
	@echo "Assert.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/System.o: ../Src/SimRobotCore2/Platform/System.cpp  | prebuild
	@echo "System.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxMass.o: ../Src/SimRobotCore2/Simulation/Masses/BoxMass.cpp  | prebuild
	@echo "BoxMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Scene.o: ../Src/SimRobotCore2/Simulation/Scene.cpp  | prebuild
	@echo "Scene.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SingleDistanceSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/SingleDistanceSensor.cpp  | prebuild
	@echo "SingleDistanceSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CylinderGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/CylinderGeometry.cpp  | prebuild
	@echo "CylinderGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/InertiaMatrixMass.o: ../Src/SimRobotCore2/Simulation/Masses/InertiaMatrixMass.cpp  | prebuild
	@echo "InertiaMatrixMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/BoxAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/BoxAppearance.cpp  | prebuild
	@echo "BoxAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Axis.o: ../Src/SimRobotCore2/Simulation/Axis.cpp  | prebuild
	@echo "Axis.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Sensor.o: ../Src/SimRobotCore2/Simulation/Sensor.cpp  | prebuild
	@echo "Sensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObject.o: ../Src/SimRobotCore2/Simulation/SimObject.cpp  | prebuild
	@echo "SimObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Geometry.o: ../Src/SimRobotCore2/Simulation/Geometries/Geometry.cpp  | prebuild
	@echo "Geometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Mass.o: ../Src/SimRobotCore2/Simulation/Masses/Mass.cpp  | prebuild
	@echo "Mass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Vector3.o: ../Src/SimRobotCore2/Tools/Vector3.cpp  | prebuild
	@echo "Vector3.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Accelerometer.o: ../Src/SimRobotCore2/Simulation/Sensors/Accelerometer.cpp  | prebuild
	@echo "Accelerometer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Simulation.o: ../Src/SimRobotCore2/Simulation/Simulation.cpp  | prebuild
	@echo "Simulation.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereGeometry.o: ../Src/SimRobotCore2/Simulation/Geometries/SphereGeometry.cpp  | prebuild
	@echo "SphereGeometry.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SphereMass.o: ../Src/SimRobotCore2/Simulation/Masses/SphereMass.cpp  | prebuild
	@echo "SphereMass.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ComplexAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/ComplexAppearance.cpp  | prebuild
	@echo "ComplexAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Body.o: ../Src/SimRobotCore2/Simulation/Body.cpp  | prebuild
	@echo "Body.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/OpenGLTools.o: ../Src/SimRobotCore2/Tools/OpenGLTools.cpp  | prebuild
	@echo "OpenGLTools.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Element.o: ../Src/SimRobotCore2/Parser/Element.cpp  | prebuild
	@echo "Element.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Reader.o: ../Src/SimRobotCore2/Parser/Reader.cpp  | prebuild
	@echo "Reader.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/OffscreenRenderer.o: ../Src/SimRobotCore2/Platform/OffscreenRenderer.cpp  | prebuild
	@echo "OffscreenRenderer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/GraphicalObject.o: ../Src/SimRobotCore2/Simulation/GraphicalObject.cpp  | prebuild
	@echo "GraphicalObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Matrix3x3.o: ../Src/SimRobotCore2/Tools/Matrix3x3.cpp  | prebuild
	@echo "Matrix3x3.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Gyroscope.o: ../Src/SimRobotCore2/Simulation/Sensors/Gyroscope.cpp  | prebuild
	@echo "Gyroscope.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/PrimaryObject.o: ../Src/SimRobotCore2/Simulation/PrimaryObject.cpp  | prebuild
	@echo "PrimaryObject.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ApproxDistanceSensor.o: ../Src/SimRobotCore2/Simulation/Sensors/ApproxDistanceSensor.cpp  | prebuild
	@echo "ApproxDistanceSensor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/ServoMotor.o: ../Src/SimRobotCore2/Simulation/Motors/ServoMotor.cpp  | prebuild
	@echo "ServoMotor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Bumper.o: ../Src/SimRobotCore2/Simulation/Sensors/Bumper.cpp  | prebuild
	@echo "Bumper.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SensorWidget.o: ../Src/SimRobotCore2/SensorWidget.cpp  | prebuild
	@echo "SensorWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Hinge.o: ../Src/SimRobotCore2/Simulation/Joints/Hinge.cpp  | prebuild
	@echo "Hinge.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Actuator.o: ../Src/SimRobotCore2/Simulation/Actuator.cpp  | prebuild
	@echo "Actuator.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/CylinderAppearance.o: ../Src/SimRobotCore2/Simulation/Appearances/CylinderAppearance.cpp  | prebuild
	@echo "CylinderAppearance.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Compound.o: ../Src/SimRobotCore2/Simulation/Compound.cpp  | prebuild
	@echo "Compound.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SimObjectRenderer.o: ../Src/SimRobotCore2/SimObjectRenderer.cpp  | prebuild
	@echo "SimObjectRenderer.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/VelocityMotor.o: ../Src/SimRobotCore2/Simulation/Motors/VelocityMotor.cpp  | prebuild
	@echo "VelocityMotor.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Slider.o: ../Src/SimRobotCore2/Simulation/Joints/Slider.cpp  | prebuild
	@echo "Slider.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobotCore2.cpp: ../Src/SimRobotCore2/SimRobotCore2.qrc ../Src/SimRobotCore2/Icons/DragPlane.png ../Src/SimRobotCore2/Icons/arrow_rotate_clockwise.png ../Src/SimRobotCore2/Icons/brick.png ../Src/SimRobotCore2/Icons/bricks.png ../Src/SimRobotCore2/Icons/camera.png ../Src/SimRobotCore2/Icons/chart_line.png ../Src/SimRobotCore2/Icons/layers.png ../Src/SimRobotCore2/Icons/link.png ../Src/SimRobotCore2/Icons/note.png ../Src/SimRobotCore2/Icons/opening_angle.png ../Src/SimRobotCore2/Icons/slider.png ../Src/SimRobotCore2/Icons/transmit_go.png ../Src/SimRobotCore2/SimRobotCore2.qrc | prebuild
	@echo "SimRobotCore2.qrc (Qt rcc)"
	@rcc -name SimRobotCore2 ../Src/SimRobotCore2/SimRobotCore2.qrc -o $(INTDIR)/qrc_SimRobotCore2.cpp

$(INTDIR)/moc_SensorWidget.cpp: ../Src/SimRobotCore2/SensorWidget.h  | prebuild
	@echo "SensorWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/SensorWidget.h -o $(INTDIR)/moc_SensorWidget.cpp

$(INTDIR)/moc_ActuatorsWidget.cpp: ../Src/SimRobotCore2/ActuatorsWidget.h  | prebuild
	@echo "ActuatorsWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/ActuatorsWidget.h -o $(INTDIR)/moc_ActuatorsWidget.cpp

$(INTDIR)/moc_SimObjectWidget.cpp: ../Src/SimRobotCore2/SimObjectWidget.h  | prebuild
	@echo "SimObjectWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I../Src/SimRobotCore2 -I../Util/glew/Linux/include -I../Util/libxml2/include -I../Util/ode/Linux/include -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 ../Src/SimRobotCore2/SimObjectWidget.h -o $(INTDIR)/moc_SimObjectWidget.cpp

$(INTDIR):
	@mkdir -p $(INTDIR)

ifneq ($(INTDIR),$(OUTDIR))
$(OUTDIR):
	@mkdir -p $(OUTDIR)
endif

prebuild: $(INTDIR) $(OUTDIR)
	@echo "------ Building $(PROJECTNAME) ($(CONFIG)) ------"

clean:
	@echo "------ Cleaning $(PROJECTNAME) ($(CONFIG)) ------"
	@echo Cleaning...
	-@rm -rf $(OBJECTS) $(PCHOBJECT) $(CUSTOMOBJECTS) $(TARGET) $(OBJECTS:%.o=%.d) $(PCHOBJECT:%.gch=%.d)

-include $(OBJECTS:%.o=%.d)

endif

%.h: ;
%.hh: ;
%.hxx: ;
%.hpp: ;
%.c: ;
%.cc: ;
%.cxx: ;
%.cpp: ;
%.d: ;

dist: ;

distclean: ;

