

# This file was generated by zbuildgen. Don't edit this file! Edit "SimRobot.make.zbuild" instead.


SOLUTIONDIR ?= $(CURDIR)

ifeq ($(CONFIG),Debug)

PROJECTNAME := SimRobot
CONFIG := Debug
OUTDIR := $(SOLUTIONDIR)/../Build/SimRobot/Linux/$(CONFIG)
INTDIR := $(SOLUTIONDIR)/../Build/SimRobot/Linux/$(CONFIG)
TARGET := $(OUTDIR)/SimRobot
OBJECTS := \
	$(INTDIR)/moc_MainWindow.o\
	$(INTDIR)/moc_RegisteredDockWidget.o\
	$(INTDIR)/moc_SceneGraphDockWidget.o\
	$(INTDIR)/moc_StatusBar.o\
	$(INTDIR)/qrc_SimRobot.o\
	$(INTDIR)/SceneGraphDockWidget.o\
	$(INTDIR)/Main.o\
	$(INTDIR)/StatusBar.o\
	$(INTDIR)/MainWindow.o\
	$(INTDIR)/RegisteredDockWidget.o\

PCHOBJECT := 
CUSTOMOBJECTS := \
	$(OUTDIR)/libSimRobotCore2.so\
	$(INTDIR)/qrc_SimRobot.cpp\
	$(OUTDIR)/libSimRobotEditor.so\
	$(INTDIR)/moc_StatusBar.cpp\
	$(OUTDIR)/help.qch\
	$(INTDIR)/moc_RegisteredDockWidget.cpp\
	$(OUTDIR)/helpcollection.qhc\
	$(INTDIR)/moc_SceneGraphDockWidget.cpp\
	$(OUTDIR)/libSimRobotHelp.so\
	$(OUTDIR)/libFactory.so\
	$(OUTDIR)/libSimpleVehicle.so\
	$(INTDIR)/moc_MainWindow.cpp\

DEPENDENCIES := 

DEFINES := -D"LINUX" -D"QT_NO_DEBUG" -D"QT_SHARED" -D"QT_GUI_LIB" -D"QT_CORE_LIB" -D"_DEBUG"
INCPATHS := -I"$(INTDIR)" -I"/usr/include/qt4/QtCore" -I"/usr/include/qt4/QtGui" -I"/usr/include/qt4"
LIBPATHS := 
LIBS := -lrt -lpthread -lQtGui -lQtCore -lQtSvg

BUILDFLAGS := -MMD $(DEFINES) $(INCPATHS)    -pipe -Wall -Wno-strict-aliasing -Wno-non-virtual-dtor -Wno-deprecated -Wno-ignored-qualifiers -g
LINKFLAGS :=    $(LIBPATHS) $(LIBS)

.PHONY: all prebuild clean dist distclean

all: $(TARGET)

$(TARGET): $(OBJECTS) $(CUSTOMOBJECTS) $(DEPENDENCIES)
	@echo Linking...
	@$(CXX) -o $@ $(OBJECTS) $(LDFLAGS) $(LINKFLAGS) 

$(INTDIR)/moc_MainWindow.o: $(INTDIR)/moc_MainWindow.cpp  | prebuild
	@echo "moc_MainWindow.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_RegisteredDockWidget.o: $(INTDIR)/moc_RegisteredDockWidget.cpp  | prebuild
	@echo "moc_RegisteredDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SceneGraphDockWidget.o: $(INTDIR)/moc_SceneGraphDockWidget.cpp  | prebuild
	@echo "moc_SceneGraphDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_StatusBar.o: $(INTDIR)/moc_StatusBar.cpp  | prebuild
	@echo "moc_StatusBar.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobot.o: $(INTDIR)/qrc_SimRobot.cpp  | prebuild
	@echo "qrc_SimRobot.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SceneGraphDockWidget.o: ../Src/SimRobot/SceneGraphDockWidget.cpp  | prebuild
	@echo "SceneGraphDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Main.o: ../Src/SimRobot/Main.cpp  | prebuild
	@echo "Main.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/StatusBar.o: ../Src/SimRobot/StatusBar.cpp  | prebuild
	@echo "StatusBar.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/MainWindow.o: ../Src/SimRobot/MainWindow.cpp  | prebuild
	@echo "MainWindow.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/RegisteredDockWidget.o: ../Src/SimRobot/RegisteredDockWidget.cpp  | prebuild
	@echo "RegisteredDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(OUTDIR)/libSimRobotCore2.so: ../Build/SimRobotCore2/Linux/Debug/libSimRobotCore2.so  | prebuild
	@echo "libSimRobotCore2.so (copy)"
	@cp "../Build/SimRobotCore2/Linux/Debug/libSimRobotCore2.so" "$(OUTDIR)/libSimRobotCore2.so"

$(INTDIR)/qrc_SimRobot.cpp: ../Src/SimRobot/SimRobot.qrc ../Src/SimRobot/Icons/SimRobot.png ../Src/SimRobot/Icons/application_side_tree.png ../Src/SimRobot/Icons/arrow_redo.png ../Src/SimRobot/Icons/arrow_undo.png ../Src/SimRobot/Icons/control_play_blue.png ../Src/SimRobot/Icons/control_start_blue.png ../Src/SimRobot/Icons/control_step_blue.png ../Src/SimRobot/Icons/cut.png ../Src/SimRobot/Icons/disk.png ../Src/SimRobot/Icons/folder.png ../Src/SimRobot/Icons/folder_page.png ../Src/SimRobot/Icons/page_copy.png ../Src/SimRobot/Icons/page_paste.png ../Src/SimRobot/Icons/tag_green.png ../Src/SimRobot/Icons/textfield.png ../Src/SimRobot/SimRobot.qrc ../Src/SimRobot/SimRobot.rc | prebuild
	@echo "SimRobot.qrc (Qt rcc)"
	@rcc -name SimRobot ../Src/SimRobot/SimRobot.qrc -o $(INTDIR)/qrc_SimRobot.cpp

$(OUTDIR)/libSimRobotEditor.so: ../Build/SimRobotEditor/Linux/Debug/libSimRobotEditor.so  | prebuild
	@echo "libSimRobotEditor.so (copy)"
	@cp "../Build/SimRobotEditor/Linux/Debug/libSimRobotEditor.so" "$(OUTDIR)/libSimRobotEditor.so"

$(INTDIR)/moc_StatusBar.cpp: ../Src/SimRobot/StatusBar.h  | prebuild
	@echo "StatusBar.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -D_DEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/StatusBar.h -o $(INTDIR)/moc_StatusBar.cpp

$(OUTDIR)/help.qch: ../Build/SimRobotHelp/Help/help.qch  | prebuild
	@echo "help.qch (copy)"
	@cp "../Build/SimRobotHelp/Help/help.qch" "$(OUTDIR)/help.qch"

$(INTDIR)/moc_RegisteredDockWidget.cpp: ../Src/SimRobot/RegisteredDockWidget.h  | prebuild
	@echo "RegisteredDockWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -D_DEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/RegisteredDockWidget.h -o $(INTDIR)/moc_RegisteredDockWidget.cpp

$(OUTDIR)/helpcollection.qhc: ../Build/SimRobotHelp/Help/helpcollection.qhc  | prebuild
	@echo "helpcollection.qhc (copy)"
	@cp "../Build/SimRobotHelp/Help/helpcollection.qhc" "$(OUTDIR)/helpcollection.qhc"

$(INTDIR)/moc_SceneGraphDockWidget.cpp: ../Src/SimRobot/SceneGraphDockWidget.h  | prebuild
	@echo "SceneGraphDockWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -D_DEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/SceneGraphDockWidget.h -o $(INTDIR)/moc_SceneGraphDockWidget.cpp

$(OUTDIR)/libSimRobotHelp.so: ../Build/SimRobotHelp/Linux/Debug/libSimRobotHelp.so  | prebuild
	@echo "libSimRobotHelp.so (copy)"
	@cp "../Build/SimRobotHelp/Linux/Debug/libSimRobotHelp.so" "$(OUTDIR)/libSimRobotHelp.so"

$(OUTDIR)/libFactory.so: ../Build/Factory/Linux/Debug/libFactory.so  | prebuild
	@echo "libFactory.so (copy)"
	@cp "../Build/Factory/Linux/Debug/libFactory.so" "$(OUTDIR)/libFactory.so"

$(OUTDIR)/libSimpleVehicle.so: ../Build/SimpleVehicle/Linux/Debug/libSimpleVehicle.so  | prebuild
	@echo "libSimpleVehicle.so (copy)"
	@cp "../Build/SimpleVehicle/Linux/Debug/libSimpleVehicle.so" "$(OUTDIR)/libSimpleVehicle.so"

$(INTDIR)/moc_MainWindow.cpp: ../Src/SimRobot/MainWindow.h  | prebuild
	@echo "MainWindow.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -D_DEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/MainWindow.h -o $(INTDIR)/moc_MainWindow.cpp

$(INTDIR):
	@mkdir -p $(INTDIR)

ifneq ($(INTDIR),$(OUTDIR))
$(OUTDIR):
	@mkdir -p $(OUTDIR)
endif

prebuild: $(INTDIR) $(OUTDIR)
	@echo "------ Building $(PROJECTNAME) ($(CONFIG)) ------"

clean:
	@echo "------ Cleaning $(PROJECTNAME) ($(CONFIG)) ------"
	@echo Cleaning...
	-@rm -rf $(OBJECTS) $(PCHOBJECT) $(CUSTOMOBJECTS) $(TARGET) $(OBJECTS:%.o=%.d) $(PCHOBJECT:%.gch=%.d)

-include $(OBJECTS:%.o=%.d)

else

PROJECTNAME := SimRobot
CONFIG := Release
OUTDIR := $(SOLUTIONDIR)/../Build/SimRobot/Linux/$(CONFIG)
INTDIR := $(SOLUTIONDIR)/../Build/SimRobot/Linux/$(CONFIG)
TARGET := $(OUTDIR)/SimRobot
OBJECTS := \
	$(INTDIR)/moc_MainWindow.o\
	$(INTDIR)/moc_RegisteredDockWidget.o\
	$(INTDIR)/moc_SceneGraphDockWidget.o\
	$(INTDIR)/moc_StatusBar.o\
	$(INTDIR)/qrc_SimRobot.o\
	$(INTDIR)/SceneGraphDockWidget.o\
	$(INTDIR)/Main.o\
	$(INTDIR)/StatusBar.o\
	$(INTDIR)/MainWindow.o\
	$(INTDIR)/RegisteredDockWidget.o\

PCHOBJECT := 
CUSTOMOBJECTS := \
	$(OUTDIR)/libSimRobotCore2.so\
	$(INTDIR)/qrc_SimRobot.cpp\
	$(OUTDIR)/libSimRobotEditor.so\
	$(INTDIR)/moc_StatusBar.cpp\
	$(OUTDIR)/help.qch\
	$(INTDIR)/moc_RegisteredDockWidget.cpp\
	$(OUTDIR)/helpcollection.qhc\
	$(INTDIR)/moc_SceneGraphDockWidget.cpp\
	$(OUTDIR)/libSimRobotHelp.so\
	$(OUTDIR)/libFactory.so\
	$(OUTDIR)/libSimpleVehicle.so\
	$(INTDIR)/moc_MainWindow.cpp\

DEPENDENCIES := 

DEFINES := -D"LINUX" -D"QT_NO_DEBUG" -D"QT_SHARED" -D"QT_GUI_LIB" -D"QT_CORE_LIB" -D"NDEBUG"
INCPATHS := -I"$(INTDIR)" -I"/usr/include/qt4/QtCore" -I"/usr/include/qt4/QtGui" -I"/usr/include/qt4"
LIBPATHS := 
LIBS := -lrt -lpthread -lQtGui -lQtCore -lQtSvg

BUILDFLAGS := -MMD $(DEFINES) $(INCPATHS)    -pipe -Wall -Wno-strict-aliasing -Wno-non-virtual-dtor -Wno-deprecated -Wno-ignored-qualifiers -O3 -fomit-frame-pointer
LINKFLAGS :=   -s $(LIBPATHS) $(LIBS)

.PHONY: all prebuild clean dist distclean

all: $(TARGET)

$(TARGET): $(OBJECTS) $(CUSTOMOBJECTS) $(DEPENDENCIES)
	@echo Linking...
	@$(CXX) -o $@ $(OBJECTS) $(LDFLAGS) $(LINKFLAGS) 

$(INTDIR)/moc_MainWindow.o: $(INTDIR)/moc_MainWindow.cpp  | prebuild
	@echo "moc_MainWindow.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_RegisteredDockWidget.o: $(INTDIR)/moc_RegisteredDockWidget.cpp  | prebuild
	@echo "moc_RegisteredDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_SceneGraphDockWidget.o: $(INTDIR)/moc_SceneGraphDockWidget.cpp  | prebuild
	@echo "moc_SceneGraphDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/moc_StatusBar.o: $(INTDIR)/moc_StatusBar.cpp  | prebuild
	@echo "moc_StatusBar.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/qrc_SimRobot.o: $(INTDIR)/qrc_SimRobot.cpp  | prebuild
	@echo "qrc_SimRobot.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/SceneGraphDockWidget.o: ../Src/SimRobot/SceneGraphDockWidget.cpp  | prebuild
	@echo "SceneGraphDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/Main.o: ../Src/SimRobot/Main.cpp  | prebuild
	@echo "Main.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/StatusBar.o: ../Src/SimRobot/StatusBar.cpp  | prebuild
	@echo "StatusBar.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/MainWindow.o: ../Src/SimRobot/MainWindow.cpp  | prebuild
	@echo "MainWindow.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(INTDIR)/RegisteredDockWidget.o: ../Src/SimRobot/RegisteredDockWidget.cpp  | prebuild
	@echo "RegisteredDockWidget.cpp"
	@$(CXX) $(CXXFLAGS) $(BUILDFLAGS) -o $@ -c $<

$(OUTDIR)/libSimRobotCore2.so: ../Build/SimRobotCore2/Linux/Release/libSimRobotCore2.so  | prebuild
	@echo "libSimRobotCore2.so (copy)"
	@cp "../Build/SimRobotCore2/Linux/Release/libSimRobotCore2.so" "$(OUTDIR)/libSimRobotCore2.so"

$(INTDIR)/qrc_SimRobot.cpp: ../Src/SimRobot/SimRobot.qrc ../Src/SimRobot/Icons/SimRobot.png ../Src/SimRobot/Icons/application_side_tree.png ../Src/SimRobot/Icons/arrow_redo.png ../Src/SimRobot/Icons/arrow_undo.png ../Src/SimRobot/Icons/control_play_blue.png ../Src/SimRobot/Icons/control_start_blue.png ../Src/SimRobot/Icons/control_step_blue.png ../Src/SimRobot/Icons/cut.png ../Src/SimRobot/Icons/disk.png ../Src/SimRobot/Icons/folder.png ../Src/SimRobot/Icons/folder_page.png ../Src/SimRobot/Icons/page_copy.png ../Src/SimRobot/Icons/page_paste.png ../Src/SimRobot/Icons/tag_green.png ../Src/SimRobot/Icons/textfield.png ../Src/SimRobot/SimRobot.qrc ../Src/SimRobot/SimRobot.rc | prebuild
	@echo "SimRobot.qrc (Qt rcc)"
	@rcc -name SimRobot ../Src/SimRobot/SimRobot.qrc -o $(INTDIR)/qrc_SimRobot.cpp

$(OUTDIR)/libSimRobotEditor.so: ../Build/SimRobotEditor/Linux/Release/libSimRobotEditor.so  | prebuild
	@echo "libSimRobotEditor.so (copy)"
	@cp "../Build/SimRobotEditor/Linux/Release/libSimRobotEditor.so" "$(OUTDIR)/libSimRobotEditor.so"

$(INTDIR)/moc_StatusBar.cpp: ../Src/SimRobot/StatusBar.h  | prebuild
	@echo "StatusBar.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/StatusBar.h -o $(INTDIR)/moc_StatusBar.cpp

$(OUTDIR)/help.qch: ../Build/SimRobotHelp/Help/help.qch  | prebuild
	@echo "help.qch (copy)"
	@cp "../Build/SimRobotHelp/Help/help.qch" "$(OUTDIR)/help.qch"

$(INTDIR)/moc_RegisteredDockWidget.cpp: ../Src/SimRobot/RegisteredDockWidget.h  | prebuild
	@echo "RegisteredDockWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/RegisteredDockWidget.h -o $(INTDIR)/moc_RegisteredDockWidget.cpp

$(OUTDIR)/helpcollection.qhc: ../Build/SimRobotHelp/Help/helpcollection.qhc  | prebuild
	@echo "helpcollection.qhc (copy)"
	@cp "../Build/SimRobotHelp/Help/helpcollection.qhc" "$(OUTDIR)/helpcollection.qhc"

$(INTDIR)/moc_SceneGraphDockWidget.cpp: ../Src/SimRobot/SceneGraphDockWidget.h  | prebuild
	@echo "SceneGraphDockWidget.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/SceneGraphDockWidget.h -o $(INTDIR)/moc_SceneGraphDockWidget.cpp

$(OUTDIR)/libSimRobotHelp.so: ../Build/SimRobotHelp/Linux/Release/libSimRobotHelp.so  | prebuild
	@echo "libSimRobotHelp.so (copy)"
	@cp "../Build/SimRobotHelp/Linux/Release/libSimRobotHelp.so" "$(OUTDIR)/libSimRobotHelp.so"

$(OUTDIR)/libFactory.so: ../Build/Factory/Linux/Release/libFactory.so  | prebuild
	@echo "libFactory.so (copy)"
	@cp "../Build/Factory/Linux/Release/libFactory.so" "$(OUTDIR)/libFactory.so"

$(OUTDIR)/libSimpleVehicle.so: ../Build/SimpleVehicle/Linux/Release/libSimpleVehicle.so  | prebuild
	@echo "libSimpleVehicle.so (copy)"
	@cp "../Build/SimpleVehicle/Linux/Release/libSimpleVehicle.so" "$(OUTDIR)/libSimpleVehicle.so"

$(INTDIR)/moc_MainWindow.cpp: ../Src/SimRobot/MainWindow.h  | prebuild
	@echo "MainWindow.h (Qt moc)"
	@moc-qt4 -DLINUX -DQT_NO_DEBUG -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 ../Src/SimRobot/MainWindow.h -o $(INTDIR)/moc_MainWindow.cpp

$(INTDIR):
	@mkdir -p $(INTDIR)

ifneq ($(INTDIR),$(OUTDIR))
$(OUTDIR):
	@mkdir -p $(OUTDIR)
endif

prebuild: $(INTDIR) $(OUTDIR)
	@echo "------ Building $(PROJECTNAME) ($(CONFIG)) ------"

clean:
	@echo "------ Cleaning $(PROJECTNAME) ($(CONFIG)) ------"
	@echo Cleaning...
	-@rm -rf $(OBJECTS) $(PCHOBJECT) $(CUSTOMOBJECTS) $(TARGET) $(OBJECTS:%.o=%.d) $(PCHOBJECT:%.gch=%.d)

-include $(OBJECTS:%.o=%.d)

endif

%.h: ;
%.hh: ;
%.hxx: ;
%.hpp: ;
%.c: ;
%.cc: ;
%.cxx: ;
%.cpp: ;
%.d: ;

dist: ;

distclean: ;

