 motion_id = keeperJumpLeftSign
"sit down after standing

label start
label sitting

"HY HP  LSR LEY LER  RSR REY RER  LHYP LHR LHP LKP LAP LAR  RHYP RHR RHP RKP RAP RAR  Int Dur

* * 90.0 13.5 7.6 -14.5 -68.7 14.2 8.1 -11.1 -0.4 1.9 -51.9 122.6 -70 -1.7 -0.4 -0.6 -52.2 121.9 -70.7 0.6 1 500
* * - - - - - - - - * - - - - - - * * - - -  0 100

label repeat

* * - - - - - - - - * - - - - - - * * - - -  0 100

transition keeperJumpLeftSign keeperJumpLeftSign repeat
transition allMotions goUp start
