motion_id = keeperStandJumpLeft

label start         

" ein bisschen in die knie und arme hoch
"HY HP LSP LSR LEY LER RSP RSR REY RER LHYP LHR LHP LKP LAP LAR RHYP RHR RHP RKP RAP RAR  Int  Dur
 0  0  30  20  -70 0   *   *   *   *   0    0   -40 80  -40 0   0    0   -40 80  -40 0    1    2000

"arme ganz hoch / leicht abstoﬂen / linken fuﬂ anwinkeln
"HY HP LSP LSR LEY LER RSP RSR REY RER LHYP LHR LHP LKP LAP LAR RHYP RHR RHP RKP RAP RAR  Int  Dur
 *  *  60  40  -30 -20 *   *   *   *   *    *   *   *   *   -10 *    *   -30 60  -30 *    1    1000 
 
"linkes bein weiter anwinkel / beine etwas auﬂeinander / linken fuﬂ weiter anwinkeln
"HY HP LSP LSR LEY LER RSP RSR REY RER LHYP LHR LHP LKP LAP LAR RHYP RHR RHP RKP RAP RAR  Int  Dur
 *  *  90  60  0   -40 *   *   *   *   *    -10 -45 90  -45 -20 *    -10 *   *   *   *    1    2000 
 *  *  *   *   *   *   *   *   *   *   *    *   *   *   *   *   *    *   *   *   *   *    1    1000 
 
label repeat
 - - - - - - - - - - - - - - - - - - - - - - 0 100 


transition keeperStandJumpLeft keeperStandJumpLeft repeat
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

transition allMotions extern start
